name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build IPA
        run: |
          xcodebuild -scheme Cashapp \
          -project Cashapp.xcodeproj \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/Cashapp.xcarchive archive

          xcodebuild -exportArchive \
          -archivePath build/Cashapp.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build/

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: CashApp-iOS
          path: build/*.ipa
